name: Tests
on:
  push:
    branches: 
      - main
      - dev
  pull_request:
    branches: 
      - main
      - dev
jobs:
  unit_tests:
    name: Run Unit Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
      - name: Run Tests
        run: make test
